name: PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@master
        with:
          success-state: Title follows the specification.
          failure-state: Title does not follow the specification.
          context-name: title
          preset: conventional-changelog-angular@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: install
        run: npm install --no-optional
      - name: lint
        run: ./scripts/dev-env/run.sh npm run lint
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Generate layout.json and update manifest.json
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh
          ./scripts/dev-env/run.sh ./scripts/build.sh

          mkdir tmp_A32NX
          mv A32NX tmp_A32NX/
          mv tmp_A32NX A32NX
      - uses: actions/upload-artifact@v2
        with:
          name: A32NX
          path: A32NX
